"""Test suite covering catalog, cart, merging, checkout, and security."""
from decimal import Decimal

from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from .models import Cart, CartItem, Category, Order, Product
from .services import InsufficientStock, add_to_cart, get_or_create_cart, place_order


class CatalogTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name="Audio")
        cls.p1 = Product.objects.create(category=cls.cat, name="Headphones", price=Decimal("199.00"), stock=5)
        cls.p2 = Product.objects.create(category=cls.cat, name="Speaker", price=Decimal("59.00"), stock=0)
        cls.hidden = Product.objects.create(category=cls.cat, name="Secret", price=Decimal("9.00"), stock=3, is_active=False)

    def test_list_shows_active_only(self):
        res = self.client.get(reverse("store:product_list"))
        self.assertEqual(res.status_code, 200)
        self.assertContains(res, "Headphones")
        self.assertNotContains(res, "Secret")

    def test_search_filters(self):
        res = self.client.get(reverse("store:search"), {"q": "speaker"})
        self.assertContains(res, "Speaker")
        self.assertNotContains(res, "Headphones")

    def test_category_filter(self):
        res = self.client.get(self.cat.get_absolute_url())
        self.assertContains(res, "Headphones")

    def test_detail_404_for_inactive(self):
        self.assertEqual(self.client.get(self.hidden.get_absolute_url()).status_code, 404)

    def test_slug_autogenerated_and_unique(self):
        a = Product.objects.create(category=self.cat, name="Same Name", price=Decimal("1.00"), stock=1)
        b = Product.objects.create(category=self.cat, name="Same Name", price=Decimal("1.00"), stock=1)
        self.assertNotEqual(a.slug, b.slug)


class CartServiceTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name="Audio")
        cls.product = Product.objects.create(category=cls.cat, name="Headphones", price=Decimal("199.00"), stock=3)

    def test_add_increments(self):
        cart = Cart.objects.create(session_key="abc")
        add_to_cart(cart, self.product, 1)
        add_to_cart(cart, self.product, 1)
        self.assertEqual(cart.items.get(product=self.product).quantity, 2)

    def test_add_beyond_stock_raises(self):
        cart = Cart.objects.create(session_key="abc")
        with self.assertRaises(InsufficientStock):
            add_to_cart(cart, self.product, 99)

    def test_failed_add_leaves_no_stray_row(self):
        """Regression: a rejected add must not create an empty cart line."""
        cart = Cart.objects.create(session_key="abc")
        with self.assertRaises(InsufficientStock):
            add_to_cart(cart, self.product, 99)
        self.assertEqual(cart.items.count(), 0)

    def test_failed_add_preserves_existing_quantity(self):
        cart = Cart.objects.create(session_key="abc")
        add_to_cart(cart, self.product, 2)
        with self.assertRaises(InsufficientStock):
            add_to_cart(cart, self.product, 5)  # 2 + 5 > 3
        self.assertEqual(cart.items.get(product=self.product).quantity, 2)


class CartMergeTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name="Audio")
        cls.product = Product.objects.create(category=cls.cat, name="Headphones", price=Decimal("199.00"), stock=10)
        cls.user = User.objects.create_user("merger", password="Shopping99x!")

    def test_guest_cart_merges_on_login(self):
        # Guest adds an item.
        self.client.post(
            reverse("store:cart_add", args=[self.product.id]),
            {"quantity": 2, "next": reverse("store:cart_detail")},
        )
        self.assertEqual(CartItem.objects.count(), 1)

        # Logging in merges the guest cart into the user's cart.
        self.client.post(reverse("accounts:login"), {"username": "merger", "password": "Shopping99x!"})
        user_cart = Cart.objects.get(user=self.user)
        self.assertEqual(user_cart.items.get(product=self.product).quantity, 2)
        # The anonymous cart is gone.
        self.assertFalse(Cart.objects.filter(user__isnull=True).exists())

    def test_merge_combines_and_clamps_to_stock(self):
        self.product.stock = 5
        self.product.save()
        # User already has 4 in their cart.
        user_cart = Cart.objects.create(user=self.user)
        CartItem.objects.create(cart=user_cart, product=self.product, quantity=4)
        # Guest adds 3 more, then logs in (4 + 3 = 7, clamped to stock 5).
        self.client.post(reverse("store:cart_add", args=[self.product.id]), {"quantity": 3})
        self.client.post(reverse("accounts:login"), {"username": "merger", "password": "Shopping99x!"})
        self.assertEqual(user_cart.items.get(product=self.product).quantity, 5)


class CheckoutTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name="Audio")
        cls.product = Product.objects.create(category=cls.cat, name="Headphones", price=Decimal("199.00"), stock=5)
        cls.user = User.objects.create_user("buyer", password="Shopping99x!")

    SHIPPING = {
        "full_name": "Test Buyer", "email": "b@a.test", "phone": "555",
        "address": "1 Way", "city": "Town", "postal_code": "00001", "country": "Land",
    }

    def test_checkout_requires_login(self):
        res = self.client.get(reverse("store:checkout"))
        self.assertEqual(res.status_code, 302)
        self.assertIn(reverse("accounts:login"), res.url)

    def test_place_order_decrements_stock_and_clears_cart(self):
        cart = Cart.objects.create(user=self.user)
        CartItem.objects.create(cart=cart, product=self.product, quantity=2)
        order = place_order(cart, shipping=self.SHIPPING, user=self.user)
        self.product.refresh_from_db()
        self.assertEqual(self.product.stock, 3)
        self.assertEqual(order.total_amount, Decimal("398.00"))
        self.assertEqual(order.status, Order.Status.PAID)
        self.assertEqual(cart.items.count(), 0)

    def test_order_snapshots_price(self):
        cart = Cart.objects.create(user=self.user)
        CartItem.objects.create(cart=cart, product=self.product, quantity=1)
        order = place_order(cart, shipping=self.SHIPPING, user=self.user)
        # Change the product price afterwards — the order must not move.
        self.product.price = Decimal("999.00")
        self.product.save()
        item = order.items.first()
        self.assertEqual(item.price, Decimal("199.00"))
        self.assertEqual(item.product_name, "Headphones")

    def test_place_order_rejects_insufficient_stock(self):
        cart = Cart.objects.create(user=self.user)
        CartItem.objects.create(cart=cart, product=self.product, quantity=99)
        with self.assertRaises(InsufficientStock):
            place_order(cart, shipping=self.SHIPPING, user=self.user)
        self.product.refresh_from_db()
        self.assertEqual(self.product.stock, 5)  # unchanged — transaction rolled back
        self.assertFalse(Order.objects.exists())  # no half-written order

    def test_empty_cart_cannot_checkout(self):
        cart = Cart.objects.create(user=self.user)
        with self.assertRaises(ValueError):
            place_order(cart, shipping=self.SHIPPING, user=self.user)

    def test_full_checkout_view_flow(self):
        self.client.login(username="buyer", password="Shopping99x!")
        self.client.post(reverse("store:cart_add", args=[self.product.id]), {"quantity": 1})
        res = self.client.post(reverse("store:checkout"), self.SHIPPING)
        self.assertEqual(res.status_code, 302)
        order = Order.objects.get(user=self.user)
        self.assertIn(order.order_number, res.url)


class SecurityTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name="Audio")
        cls.product = Product.objects.create(category=cls.cat, name="Headphones", price=Decimal("199.00"), stock=5)
        cls.alice = User.objects.create_user("alice", password="Shopping99x!")
        cls.bob = User.objects.create_user("bob", password="Shopping99x!")

    def test_open_redirect_blocked(self):
        res = self.client.post(
            reverse("store:cart_add", args=[self.product.id]),
            {"quantity": 1, "next": "https://evil.example.com/phish"},
        )
        self.assertEqual(res.status_code, 302)
        self.assertNotIn("evil.example.com", res.url)

    def test_cannot_view_another_users_order(self):
        cart = Cart.objects.create(user=self.alice)
        CartItem.objects.create(cart=cart, product=self.product, quantity=1)
        order = place_order(cart, shipping={
            "full_name": "Alice", "email": "a@a.test", "phone": "1",
            "address": "x", "city": "y", "postal_code": "z", "country": "L"}, user=self.alice)
        self.client.login(username="bob", password="Shopping99x!")
        res = self.client.get(reverse("store:order_confirmation", args=[order.order_number]))
        self.assertEqual(res.status_code, 404)
